[versions]
junitVer = "5.12.2"
guavaVer = "33.4.5-jre"
jSpecifyConformanceTestVer = "0.0.0-SNAPSHOT"
checkerFrameworkVer = "3.49.1-eisop1"
plumeUtilVer = "1.10.0"

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitVer" }
guava = { module = "com.google.guava:guava", version.ref = "guavaVer" }
jspecify-conformance-tests = { module = "org.jspecify.conformance:conformance-tests", version.ref = "jSpecifyConformanceTestVer" }
jspecify-conformance-framework = { module = "org.jspecify.conformance:conformance-test-framework", version.ref = "jSpecifyConformanceTestVer" }
checkerframework-checker = { module = "io.github.eisop:checker", version.ref = "checkerFrameworkVer" }
checkerframework-framework-test = { module = "io.github.eisop:framework-test", version.ref = "checkerFrameworkVer" }
checkerframework-qual = { module = "io.github.eisop:checker-qual", version.ref = "checkerFrameworkVer" }
plume-utils = { module = "org.plumelib:plume-util", version.ref = "plumeUtilVer" }
